name: dnztrtsh
favicon: null
layout_spectrum: 1
typography_spectrum: 0.026404663920402527
title: dnztrtsh
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b1ebdc'
    - '#e3c9d6'
    - '#55bea0'
    - '#09654c'
    - '#a702e3'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.7511012975592166
  rhythmicContrast: 0.5043552017305046
purpose: []
