name: dnztrtsh
favicon: null
layout_spectrum: 0.49082
typography_spectrum: 0
title: dnztrtsh
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#be5375'
    - '#f29a4f'
    - '#cabaa5'
    - '#383932'
    - '#947f62'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
